# Generated by Django 4.0.4 on 2022-05-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('retailer_price', models.IntegerField()),
                ('distributer_price', models.IntegerField()),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pricelists')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.spreevariants')),
            ],
        ),
    ]
