# Generated by Django 4.0.4 on 2022-05-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='id',
        ),
        migrations.AlterField(
            model_name='brands',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.spreeoptionvalues'),
        ),
    ]
