# Generated by Django 4.0.4 on 2022-05-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_brands_id_alter_brands_option_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.spreeoptionvalues', unique=True),
        ),
    ]
