# Generated by Django 4.0.4 on 2022-05-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_brands_option_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spreeproducts',
            options={'ordering': ('id',)},
        ),
    ]
