# Generated by Django 4.0.4 on 2022-05-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_alter_prices_distributer_price_alter_prices_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelists',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.spreeoptionvalues'),
        ),
        migrations.AlterField(
            model_name='pricelists',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
