# Generated by Django 4.0.4 on 2022-05-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_brand_pricelists_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelists',
            name='option_value',
        ),
        migrations.AddField(
            model_name='pricelists',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.brands'),
            preserve_default=False,
        ),
    ]
